ci(ci/cd): :construction_worker: Add ENV variable for test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,6 +7,9 @@ on:
 
 jobs:
   publish-tauri:
+    env:
+      MODEL_URL: https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en-q5_1.bin
+      MODEL_SHA: c77c5766f1cef09b6b7d47f21b546cbddd4157886b3b5d6d4f709e91e66c7c2b
     permissions:
       contents: write
     strategy:
@@ -54,8 +57,8 @@ jobs:
       - name: download Whisper GGML model
         shell: bash
         run: |
-          curl -o "./src-tauri/resources/whisper-model.bin" https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny-encoder.mlmodelc.zip
-          echo "c88cbd2648e1f5415092bcf5256add463a0f19943e6938f46e8d4ffdebd47739 ./src-tauri/resources/whisper-model.bin" | sha256sum -c - || { echo "Failed to verify whisper model!"; exit 1; }
+          curl -o "./src-tauri/resources/whisper-model.bin" -L $MODEL_URL
+          echo "$MODEL_SHA ./src-tauri/resources/whisper-model.bin" | sha256sum -c - || { echo "Failed to verify whisper model!"; exit 1; }
 
       # - name: install Frontend Dependencies
       #   # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
